stages:
    - build
    - test

before_script:
    - git submodule init
    - git submodule update

build:
    stage: build
    script:
        - make

run:
    stage: test
    script:
        - make
        - echo "exit()" | ./sol r programs/interp.sol

test_boot:
    stage: test
    script:
        - make
        - ./sol r programs/test.sol | tee test_out.txt
        - diff test_out.txt data/test_out.txt

all_tests:
    stage: test
    script:
        - make
        - make test
